[DEFAULT]
dhcpbridge_flagfile=/etc/nova/nova.conf
dhcpbridge=/usr/bin/nova-dhcpbridge
state_path=/var/lib/nova
force_dhcp_release=True
verbose=True
ec2_private_dns_show_ip=True
enabled_apis=osapi_compute,metadata

transport_url = rabbit://openstack:pass@controller
auth_strategy = keystone
my_ip = 10.0.0.2
use_neutron = True
firewall_driver = nova.virt.firewall.NoopFirewallDriver

allow_migrate_to_same_host = True

scheduler_default_filters = AllHostsFilter

allow_resize_to_same_host = True

resume_guests_state_on_host_boot=true

[database]
connection=sqlite:////var/lib/nova/nova.sqlite

[api_database]
connection=sqlite:////var/lib/nova/nova.sqlite

[oslo_concurrency]
lock_path = /var/lib/nova/tmp

[libvirt]
use_virtio_for_bridges=True

[wsgi]
api_paste_config=/etc/nova/api-paste.ini

[keystone_authtoken]
auth_uri = http://controller:5000
auth_url = http://controller:35357
memcached_servers = controller:11211
auth_type = password
project_domain_name = Default
user_domain_name = Default
project_name = service
username = nova
password = pass

[vnc]
enabled = True
vncserver_listen = 0.0.0.0
vncserver_proxyclient_address = $my_ip
novncproxy_base_url = http://controller:6080/vnc_auto.html

[glance]
api_servers = http://controller:9292

[neutron]
url = http://controller:9696
auth_url = http://controller:35357
auth_type = password
project_domain_name = Default
user_domain_name = Default
region_name = RegionOne
project_name = service
username = neutron
password = pass
